platform:
    - x86

environment:
    global:
        CYG_ROOT: C:/cygwin
        CYG_MIRROR: http://cygwin.uib.no
        CYG_CACHE: C:/cygwin/var/cache/setup
    matrix:
        - 
            CYG_ARCH: x86

init:
    - 'echo System architecture: %PLATFORM%'

install:
    - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P ocaml >NUL'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'

build_script:
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && ocamlc dumpenv.ml -o dumpenv && ./dumpenv"'

